[package]
name = "loom"
version = "0.1.0"
authors = ["Betsy Haibel <betsy@wecohere.com>"]

[dependencies]
tokio-process = "0.1.5"
futures = "0.1.*"
tokio-core = "0.1.*"
tokio-io = "0.1.*"
tokio-signal = "0.1"
toml = "0.4"
serde = "1.0.27"
serde_derive = "1.0.27"